name: vietmap_flutter_gl
description: A Flutter plugin for integrating Vietmap sdk inside a Flutter application on Android, iOS platforms.
version: 1.0.5
homepage: https://github.com/vietmap-company
repository: https://github.com/vietmap-company/flutter-map-sdk

dependencies:
  flutter:
    sdk: flutter
  vietmap_gl_platform_interface: ^0.0.5

# dependency_overrides:
#   vietmap_gl_platform_interface:
#     path: ./vietmap_gl_platform_interface
  # vietmap_gl_web:
  #   path: ./vietmap_gl_web

flutter:
  plugin:
    platforms:
      android:
        package: vn.vietmap.vietmapgl
        pluginClass: VietmapGLPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      # web:
      #   default_package: mapbox_gl_web

environment:
  sdk: '>=2.12.0 <3.0.0'
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=2.0.0"
