name: vietmap_flutter_gl_web
description: Web platform implementation of vietmap_flutter_gl. This package is only intended to be used by the vietmap_flutter_gl package.
version: 0.0.1-pre.4

homepage: https://maps.vietmap.vn
repository: https://github.com/vietmap-company/vietmap_flutter_gl
issue_tracker: https://github.com/vietmap-company/vietmap_flutter_gl/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VietMapGLPlugin
        fileName: vietmap_flutter_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^4.0.17
  js: ">=0.6.7 <0.8.0"
  vietmap_gl_platform_interface: 1.0.0-pre.3
  meta: ^1.3.0

dev_dependencies:
  very_good_analysis: ^5.0.0

platforms:
  web:


topics:
  - vietmap
  - map
  - flutter-map
  - map-api
